<?php

/**
 * PlugingjShortUrlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gjShortUrlPlugin
 * @subpackage model
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlugingjShortUrlTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PlugingjShortUrlTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PlugingjShortUrl');
  }

  public function getForParameters($parameters = array())
  {
    $q = $this->createQuery('s');
    $q = $this->whereParametersFit($q, $parameters);
    $q = $this->whereActive($q);

    return $q->fetchOne();
  }

  protected function whereParametersFit(Doctrine_Query $q, $parameters)
  {
    return $q->addWhere('s.source = ?', $parameters['shorturl']);
  }

  protected function whereActive(Doctrine_Query $q)
  {
    return $q->addWhere('(s.begins_at IS NULL OR s.begins_at <= CURRENT_DATE())')
             ->addWhere('(s.expires_at IS NULL OR s.expires_at >= CURRENT_DATE())');
  }
}
