<?php
/**
 * This file is part of the gjShortUrlPlugin unit tests package.
 * (c) Christian Schaefer <schaefer.christian@guj.de>
 *
 * This class has been auto-generated by the sfPhpUnitWizardPlugin
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package    gjShortUrlPluginUnitTests
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 * @version    SVN: $Id: $
 */

/**
 * PHPUnit test for lib/routing/gjShortUrlRoute.class.php
 *
 * @package    gjShortUrlPluginUnitTests
 * @subpackage routing
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 */
class gjShortUrlRouteTest extends PHPUnit_Framework_TestCase
{
  /**
   * Test for gjShortUrlRoute::matchesUrl(url, context = Array)
   *
   * @see gjShortUrlRoute::matchesUrl()
   * @todo Implement!
   */
  public function testMatchesUrl()
  {
    $this->markTestIncomplete('A test for gjShortUrlRoute::matchesUrl() still needs to be implemented!');
  }

  /**
   * Test for gjShortUrlRoute::getObject()
   *
   * @see gjShortUrlRoute::getObject()
   * @todo Implement!
   */
  public function testGetObject()
  {
    $this->markTestIncomplete('A test for gjShortUrlRoute::getObject() still needs to be implemented!');
  }
}
