<?php
/**
 * This file is part of the gjShortUrlPlugin unit tests package.
 * (c) Christian Schaefer <schaefer.christian@guj.de>
 *
 * This class has been auto-generated by the sfPhpUnitWizardPlugin
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package    gjShortUrlPluginUnitTests
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 * @version    SVN: $Id: $
 */

/**
 * PHPUnit test for lib/model/doctrine/PlugingjShortUrlTable.class.php
 *
 * @package    gjShortUrlPluginUnitTests
 * @subpackage model
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 */
class PlugingjShortUrlTableTest extends PHPUnit_Framework_TestCase
{
  /**
   * Test for PlugingjShortUrlTable::getForParameters(parameters = Array)
   *
   * @see PlugingjShortUrlTable::getForParameters()
   * @todo Implement!
   */
  public function testGetForParameters()
  {
    $this->markTestIncomplete('A test for PlugingjShortUrlTable::getForParameters() still needs to be implemented!');
  }
}
