<?php
/**
 * This file is part of the gjShortUrlPlugin unit tests package.
 * (c) Christian Schaefer <schaefer.christian@guj.de>
 *
 * This class has been auto-generated by the sfPhpUnitWizardPlugin
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package    gjShortUrlPluginUnitTests
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 * @version    SVN: $Id: $
 */

/**
 * PHPUnit test for lib/form/doctrine/PlugingjShortUrlForm.class.php
 *
 * @package    gjShortUrlPluginUnitTests
 * @subpackage form
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 */
class PlugingjShortUrlFormTest extends PHPUnit_Framework_TestCase
{
  /**
   * Test for PlugingjShortUrlForm::setup()
   *
   * @see PlugingjShortUrlForm::setup()
   * @todo Implement!
   */
  public function testSetup()
  {
    $this->markTestIncomplete('A test for PlugingjShortUrlForm::setup() still needs to be implemented!');
  }
}
