<?php

/**
 * BasegjShortUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $source
 * @property string $target
 * @property integer $code
 * @property date $begins_at
 * @property date $expires_at
 * 
 * @method string     getSource()     Returns the current record's "source" value
 * @method string     getTarget()     Returns the current record's "target" value
 * @method integer    getCode()       Returns the current record's "code" value
 * @method date       getBeginsAt()   Returns the current record's "begins_at" value
 * @method date       getExpiresAt()  Returns the current record's "expires_at" value
 * @method gjShortUrl setSource()     Sets the current record's "source" value
 * @method gjShortUrl setTarget()     Sets the current record's "target" value
 * @method gjShortUrl setCode()       Sets the current record's "code" value
 * @method gjShortUrl setBeginsAt()   Sets the current record's "begins_at" value
 * @method gjShortUrl setExpiresAt()  Sets the current record's "expires_at" value
 * 
 * @package    gjShortUrlPluginFixtureProject
 * @subpackage model
 * @author     Christian Schaefer <caefer@ical.ly>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasegjShortUrl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gj_short_url');
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('target', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('code', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('begins_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('expires_at', 'date', null, array(
             'type' => 'date',
             ));


        $this->index('source_uniq', array(
             'fields' => 
             array(
              'source' => 
              array(
              'sorting' => 'ASC',
              'length' => 20,
              ),
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}