<?php
/**
 * This file is part of the gjShortUrlPlugin unit tests package.
 * (c) Christian Schaefer <schaefer.christian@guj.de>
 *
 * This class has been auto-generated by the sfPhpUnitWizardPlugin
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package    gjShortUrlPluginUnitTests
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 * @version    SVN: $Id: $
 */

/**
 * PHPUnit test for lib/filter/doctrine/PlugingjShortUrlFormFilter.class.php
 *
 * @package    gjShortUrlPluginUnitTests
 * @subpackage filter
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 */
class PlugingjShortUrlFormFilterTest extends PHPUnit_Framework_TestCase
{
  /**
   * @todo Implement!
   */
  public function testMe()
  {
    $this->markTestIncomplete('There were no public non-static methods defined in PlugingjShortUrlFormFilter but you should test the class anyway.');
  }
}
