<?php
/**
 * This file is part of the gjShortUrlPlugin unit tests package.
 * (c) Christian Schaefer <schaefer.christian@guj.de>
 *
 * This class has been auto-generated by the sfPhpUnitWizardPlugin
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package    gjShortUrlPluginUnitTests
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 * @version    SVN: $Id: $
 */

/**
 * PHPUnit test for config/gjShortUrlPluginConfiguration.class.php
 *
 * @package    gjShortUrlPluginUnitTests
 * @subpackage config
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 */
class gjShortUrlPluginConfigurationTest extends PHPUnit_Framework_TestCase
{
  /**
   * Test for gjShortUrlPluginConfiguration::initialize()
   *
   * @see gjShortUrlPluginConfiguration::initialize()
   */
  public function testInitialize()
  {
    $this->pluginConfiguration->initialize();
  }

  protected function setUp()
  {
    $projectConfiguration = new ProjectConfiguration(dirname(__FILE__).'/../../fixtures/project/');
    $this->pluginConfiguration = new gjShortUrlPluginConfiguration($projectConfiguration);
    if(!sfContext::hasInstance('frontend'))
    {
      sfContext::createInstance($this->projectConfiguration->getApplicationConfiguration('frontend', 'test', true));
    }
  }
}
