<?php
/**
 * This file is part of the gjShortUrlPlugin unit tests package.
 * (c) Christian Schaefer <schaefer.christian@guj.de>
 *
 * This class has been auto-generated by the sfPhpUnitWizardPlugin
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package    gjShortUrlPluginUnitTests
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 * @version    SVN: $Id: $
 */

/**
 * PHPUnit test for config/gjShortUrlPluginConfiguration.class.php
 *
 * @package    gjShortUrlPluginUnitTests
 * @subpackage config
 * @author     Christian Schaefer <schaefer.christian@guj.de>
 */
class gjShortUrlPluginConfigurationTest extends PHPUnit_Framework_TestCase
{
  /**
   * Test for gjShortUrlPluginConfiguration::initialize()
   *
   * @see gjShortUrlPluginConfiguration::initialize()
   * @todo Implement!
   */
  public function testInitialize()
  {
    $this->markTestIncomplete('A test for gjShortUrlPluginConfiguration::initialize() still needs to be implemented!');
  }
}
